// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { describe, expect, it } from 'vitest';
import { runCli } from '../src/core/dispatch.js';
import type { CliIo } from '../src/core/model.js';
import { CLI_SPEC } from '../src/commands.js';
import { loadCommand } from '../src/load-command.js';

interface Harness {
  io: CliIo;
  calls: { url: string; init: RequestInit }[];
  out: string[];
  err: string[];
}

function makeIo(env: Readonly<Record<string, string>>, status = 200): Harness {
  const calls: Harness["calls"] = [];
  const out: string[] = [];
  const err: string[] = [];
  const io: CliIo = {
    env,
    fetch: (url, init) => {
      calls.push({ url, init });
      return Promise.resolve(
        new Response(JSON.stringify({ ok: true }), { status, headers: { "content-type": "application/json" } }),
      );
    },
    stdout: (text) => out.push(text),
    stderr: (text) => err.push(text),
    readFile: () => Promise.resolve(new Uint8Array([1, 2, 3])),
    sleep: () => Promise.resolve(),
    now: () => 0,
    loadCommand: (id) => loadCommand(id),
  };
  return { io, calls, out, err };
}

describe("generated CLI smoke — help/schema/dry-run/calls/exit codes", () => {
  it("--help prints usage and exits 0", async () => {
    const { io, out } = makeIo({});
    expect(await runCli(CLI_SPEC, ['--help'], io)).toBe(0);
    expect(out.join('')).toContain('usage:');
  });
  
  it("root --schema prints the machine-readable command surface", async () => {
    const { io, out } = makeIo({});
    expect(await runCli(CLI_SPEC, ['--schema'], io)).toBe(0);
    const doc = JSON.parse(out.join('')) as Record<string, unknown>;
    expect(Array.isArray(doc['x-commands'])).toBe(true);
  });
  
  it("labels create --schema prints the command's input schema", async () => {
    const { io, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke", "--schema"], io)).toBe(0);
    const doc = JSON.parse(out.join('')) as Record<string, unknown>;
    expect(doc['x-http-method']).toBe("POST");
    expect(doc['type']).toBe('object');
    expect(typeof doc['x-operation-key']).toBe('string');
  });
  
  it("labels create --dry-run prints the plan and never sends", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke", "--dry-run"], io)).toBe(0);
    expect(calls.length).toBe(0);
    const plan = JSON.parse(out.join('')) as Record<string, unknown>;
    expect(plan['dryRun']).toBe(true);
    expect(plan['method']).toBe("POST");
    expect(typeof plan['operationKey']).toBe('string');
  });
  
  it("labels create --dry-run works without credentials", async () => {
    const { io, calls, out } = makeIo({});
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke", "--dry-run"], io)).toBe(0);
    expect(calls.length).toBe(0);
    const plan = JSON.parse(out.join('')) as Record<string, unknown>;
    expect(plan['dryRun']).toBe(true);
    expect(out.join('')).not.toContain("smoke-secret");
  });
  
  it("live call --transform ok extracts the field", async () => {
    const { io, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke", "--transform", "ok"], io)).toBe(0);
    expect(JSON.parse(out.join(''))).toBe(true);
  });
  
  it("live call --format yaml is deterministic YAML", async () => {
    const { io, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke", "--format", "yaml"], io)).toBe(0);
    expect(out.join('')).toContain('ok: true');
  });
  
  it("completion fish prints a static script", async () => {
    const { io, out } = makeIo({});
    expect(await runCli(CLI_SPEC, ['completion', 'fish'], io)).toBe(0);
    expect(out.join('')).toContain('complete -c');
  });
  
  it("labels create --mock prints an example and never sends", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke", "--mock"], io)).toBe(0);
    expect(calls.length).toBe(0);
    expect(out.join('').trim().length).toBeGreaterThan(0);
  });
  
  it("root --provenance prints sdkSha matching the spec", async () => {
    const { io, out } = makeIo({});
    expect(await runCli(CLI_SPEC, ['--provenance'], io)).toBe(0);
    const doc = JSON.parse(out.join('')) as Record<string, unknown>;
    expect(doc['language']).toBe('cli');
    expect(typeof doc['sdkSha']).toBe('string');
    expect(doc['sdkSha']).toBe(CLI_SPEC.provenance.sdkSha);
  });
  it("labels create executes against a scripted fetch", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    const code = await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke"], io);
    expect(code).toBe(0);
    expect(calls.length).toBe(1);
    expect(calls[0]?.init.method).toBe("POST");
    expect(calls[0]?.url.startsWith("https://smoke.invalid/")).toBe(true);
    expect(calls[0]?.url).not.toContain('{');
    const headers = calls[0]?.init.headers as Record<string, string>;
    expect(headers["Parcel-API-Key"]).toBe("smoke-secret");
    expect(JSON.parse(out.join(''))).toEqual({ ok: true });
  });
  it("pickups cancel executes against a scripted fetch", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    const code = await runCli(CLI_SPEC, ["pickups", "cancel", "--base-url", "https://smoke.invalid", "--pickup-id", "smoke"], io);
    expect(code).toBe(0);
    expect(calls.length).toBe(1);
    expect(calls[0]?.init.method).toBe("DELETE");
    expect(calls[0]?.url.startsWith("https://smoke.invalid/")).toBe(true);
    expect(calls[0]?.url).not.toContain('{');
    const headers = calls[0]?.init.headers as Record<string, string>;
    expect(headers["Parcel-API-Key"]).toBe("smoke-secret");
    expect(JSON.parse(out.join(''))).toEqual({ ok: true });
  });
  it("rates quote executes against a scripted fetch", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    const code = await runCli(CLI_SPEC, ["rates", "quote", "--base-url", "https://smoke.invalid", "--recipient.city", "smoke", "--recipient.country", "smoke", "--recipient.line1", "smoke", "--recipient.name", "smoke", "--recipient.postal-code", "smoke", "--sender.city", "smoke", "--sender.country", "smoke", "--sender.line1", "smoke", "--sender.name", "smoke", "--sender.postal-code", "smoke"], io);
    expect(code).toBe(0);
    expect(calls.length).toBe(1);
    expect(calls[0]?.init.method).toBe("POST");
    expect(calls[0]?.url.startsWith("https://smoke.invalid/")).toBe(true);
    expect(calls[0]?.url).not.toContain('{');
    const headers = calls[0]?.init.headers as Record<string, string>;
    expect(headers["Parcel-API-Key"]).toBe("smoke-secret");
    expect(JSON.parse(out.join(''))).toEqual({ ok: true });
  });
  it("shipments cancel executes against a scripted fetch", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    const code = await runCli(CLI_SPEC, ["shipments", "cancel", "--base-url", "https://smoke.invalid", "--shipment-id", "smoke"], io);
    expect(code).toBe(0);
    expect(calls.length).toBe(1);
    expect(calls[0]?.init.method).toBe("DELETE");
    expect(calls[0]?.url.startsWith("https://smoke.invalid/")).toBe(true);
    expect(calls[0]?.url).not.toContain('{');
    const headers = calls[0]?.init.headers as Record<string, string>;
    expect(headers["Parcel-API-Key"]).toBe("smoke-secret");
    expect(JSON.parse(out.join(''))).toEqual({ ok: true });
  });
  it("retrieve executes against a scripted fetch", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    const code = await runCli(CLI_SPEC, ["retrieve", "--base-url", "https://smoke.invalid", "--tracking-number", "smoke"], io);
    expect(code).toBe(0);
    expect(calls.length).toBe(1);
    expect(calls[0]?.init.method).toBe("GET");
    expect(calls[0]?.url.startsWith("https://smoke.invalid/")).toBe(true);
    expect(calls[0]?.url).not.toContain('{');
    expect(new Headers(calls[0]?.init.headers).has("parcel-api-key")).toBe(false);
    expect(new Headers(calls[0]?.init.headers).has("authorization")).toBe(false);
    expect(JSON.parse(out.join(''))).toEqual({ ok: true });
  });
  it("webhook-endpoints create executes against a scripted fetch", async () => {
    const { io, calls, out } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    const code = await runCli(CLI_SPEC, ["webhook-endpoints", "create", "--base-url", "https://smoke.invalid", "--url", "smoke"], io);
    expect(code).toBe(0);
    expect(calls.length).toBe(1);
    expect(calls[0]?.init.method).toBe("POST");
    expect(calls[0]?.url.startsWith("https://smoke.invalid/")).toBe(true);
    expect(calls[0]?.url).not.toContain('{');
    const headers = calls[0]?.init.headers as Record<string, string>;
    expect(headers["Parcel-API-Key"]).toBe("smoke-secret");
    expect(JSON.parse(out.join(''))).toEqual({ ok: true });
  });
  it("a 404 maps to exit 6 with a typed stderr envelope", async () => {
    const { io, err } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" }, 404);
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke"], io)).toBe(6);
    expect(JSON.parse(err.join(''))).toMatchObject({ kind: 'not_found', exitCode: 6 });
  });
  
  it("an unknown command is a typed usage error (exit 2)", async () => {
    const { io, err } = makeIo({});
    expect(await runCli(CLI_SPEC, ['no-such-command'], io)).toBe(2);
    expect(JSON.parse(err.join(''))).toMatchObject({ kind: 'usage' });
  });
  
  it("a missing required flag is a typed usage error (exit 2)", async () => {
    const { io, err } = makeIo({ "PARCEL_EVENTS_API_KEY": "smoke-secret", "PARCEL_EVENTS_BEARER_TOKEN": "smoke-secret" });
    expect(await runCli(CLI_SPEC, ["labels", "create"], io)).toBe(2);
    expect(err.join('')).toContain("--idempotency-key");
  });
  
  it("missing credentials are a typed auth error (exit 4)", async () => {
    const { io, err } = makeIo({});
    expect(await runCli(CLI_SPEC, ["labels", "create", "--base-url", "https://smoke.invalid", "--idempotency-key", "smoke", "--format-body", "smoke", "--shipment-id", "smoke"], io)).toBe(4);
    expect(JSON.parse(err.join(''))).toMatchObject({ kind: 'auth' });
  });
});
