// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from '../core/model.js';

export const LABELS_COMMANDS: readonly CliCommandSpec[] = [
  {
    id: "labels.create",
    operationKey: "post /v1/labels",
    path: [
      "labels",
      "create"
    ],
    summary: "Buy and render a shipping label",
    httpMethod: "POST",
    httpPath: "/v1/labels",
    params: [
      {
        flag: "idempotency-key",
        wireName: "Idempotency-Key",
        in: "header",
        required: true,
        type: "string"
      },
      {
        flag: "format-body",
        wireName: "format",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "format"
        ]
      },
      {
        flag: "shipment-id",
        wireName: "shipment_id",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "shipment_id"
        ]
      }
    ],
    body: {
      required: true,
      contentType: "application/json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "labels.create (POST /v1/labels)",
      type: "object",
      additionalProperties: false,
      properties: {
        "idempotency-key": {
          format: "uuid",
          type: "string",
          "x-flag": "idempotency-key",
          "x-in": "header",
          "x-wire-name": "Idempotency-Key"
        },
        "format-body": {
          enum: [
            "pdf",
            "png",
            "zpl"
          ],
          type: "string",
          "x-flag": "format-body",
          "x-in": "body",
          "x-wire-name": "format",
          "x-body-path": [
            "format"
          ]
        },
        "shipment-id": {
          type: "string",
          "x-flag": "shipment-id",
          "x-in": "body",
          "x-wire-name": "shipment_id",
          "x-body-path": [
            "shipment_id"
          ]
        },
        body: {
          $ref: "#/$defs/CreateLabelRequest",
          "x-content-type": "application/json",
          "x-body-escape": true
        }
      },
      "x-http-method": "POST",
      "x-http-path": "/v1/labels",
      "x-operation-key": "post /v1/labels",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "idempotency-key",
        "format-body",
        "shipment-id"
      ],
      $defs: {
        CreateLabelRequest: {
          additionalProperties: false,
          properties: {
            format: {
              $ref: "#/$defs/LabelFormat"
            },
            page_size: {
              description: "Page size (string; one of \"a4\", \"letter\", \"four_by_six\")",
              enum: [
                "a4",
                "letter",
                "four_by_six"
              ],
              type: "string"
            },
            shipment_id: {
              description: "Shipment id (string)",
              type: "string"
            }
          },
          required: [
            "format",
            "shipment_id"
          ],
          type: "object"
        },
        LabelFormat: {
          enum: [
            "pdf",
            "png",
            "zpl"
          ],
          type: "string"
        }
      }
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      download_url: "https://downloads.parcel-events.example/labels/synthetic-label.pdf",
      expires_at: "2026-06-09T00:00:00Z",
      format: "pdf",
      id: "lbl_00000000000000000001",
      object: "label",
      price: {
        amount: "12.50",
        currency: "XTS"
      },
      shipment_id: "shp_00000000000000000001"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"download_url\": \"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\n  \"expires_at\": \"2026-06-09T00:00:00Z\",\n  \"format\": \"pdf\",\n  \"id\": \"lbl_00000000000000000001\",\n  \"object\": \"label\",\n  \"price\": {\n…\n"
    }
  },
  {
    id: "labels.retrieve",
    operationKey: "get /v1/labels/{}",
    path: [
      "labels",
      "retrieve"
    ],
    summary: "Retrieve label metadata and download URL",
    httpMethod: "GET",
    httpPath: "/v1/labels/{label_id}",
    params: [
      {
        flag: "label-id",
        wireName: "label_id",
        in: "path",
        required: true,
        type: "string"
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "labels.retrieve (GET /v1/labels/{label_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "label-id": {
          type: "string",
          "x-flag": "label-id",
          "x-in": "path",
          "x-wire-name": "label_id"
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/labels/{label_id}",
      "x-operation-key": "get /v1/labels/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "label-id"
      ]
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      download_url: "https://downloads.parcel-events.example/labels/synthetic-label.pdf",
      expires_at: "2026-06-09T00:00:00Z",
      format: "pdf",
      id: "lbl_00000000000000000001",
      object: "label",
      price: {
        amount: "12.50",
        currency: "XTS"
      },
      shipment_id: "shp_00000000000000000001"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"download_url\": \"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\n  \"expires_at\": \"2026-06-09T00:00:00Z\",\n  \"format\": \"pdf\",\n  \"id\": \"lbl_00000000000000000001\",\n  \"object\": \"label\",\n  \"price\": {\n…\n"
    }
  }
] as const as unknown as readonly CliCommandSpec[];
