// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from '../core/model.js';

export const PICKUPS_COMMANDS: readonly CliCommandSpec[] = [
  {
    id: "pickups.cancel",
    operationKey: "delete /v1/pickups/{}",
    path: [
      "pickups",
      "cancel"
    ],
    summary: "Cancel a pickup",
    httpMethod: "DELETE",
    httpPath: "/v1/pickups/{pickup_id}",
    params: [
      {
        flag: "pickup-id",
        wireName: "pickup_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "pickups.cancel (DELETE /v1/pickups/{pickup_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "pickup-id": {
          type: "string",
          pattern: "^pku_[a-z0-9]{20}$",
          "x-flag": "pickup-id",
          "x-in": "path",
          "x-wire-name": "pickup_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        }
      },
      "x-http-method": "DELETE",
      "x-http-path": "/v1/pickups/{pickup_id}",
      "x-operation-key": "delete /v1/pickups/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "pickup-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/delete-v1-pickups-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      ok: true
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"ok\": true\n}\n"
    }
  },
  {
    id: "pickups.create",
    operationKey: "post /v1/pickups",
    path: [
      "pickups",
      "create"
    ],
    summary: "Schedule a carrier pickup",
    httpMethod: "POST",
    httpPath: "/v1/pickups",
    params: [
      {
        flag: "idempotency-key",
        wireName: "Idempotency-Key",
        in: "header",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      },
      {
        flag: "address.city",
        wireName: "address.city",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "address",
          "city"
        ]
      },
      {
        flag: "address.country",
        wireName: "address.country",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "address",
          "country"
        ]
      },
      {
        flag: "address.line1",
        wireName: "address.line1",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "address",
          "line1"
        ]
      },
      {
        flag: "address.name",
        wireName: "address.name",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "address",
          "name"
        ]
      },
      {
        flag: "address.postal-code",
        wireName: "address.postal_code",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "address",
          "postal_code"
        ]
      },
      {
        flag: "window.ends-at",
        wireName: "window.ends_at",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "window",
          "ends_at"
        ]
      },
      {
        flag: "window.starts-at",
        wireName: "window.starts_at",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "window",
          "starts_at"
        ]
      }
    ],
    body: {
      required: true,
      contentType: "application/json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "pickups.create (POST /v1/pickups)",
      type: "object",
      additionalProperties: false,
      properties: {
        "idempotency-key": {
          format: "uuid",
          type: "string",
          "x-flag": "idempotency-key",
          "x-in": "header",
          "x-wire-name": "Idempotency-Key",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        },
        "address.city": {
          type: "string",
          "x-flag": "address.city",
          "x-in": "body",
          "x-wire-name": "address.city",
          "x-body-path": [
            "address",
            "city"
          ]
        },
        "address.country": {
          type: "string",
          pattern: "^[A-Z]{2}$",
          "x-flag": "address.country",
          "x-in": "body",
          "x-wire-name": "address.country",
          "x-body-path": [
            "address",
            "country"
          ]
        },
        "address.line1": {
          type: "string",
          "x-flag": "address.line1",
          "x-in": "body",
          "x-wire-name": "address.line1",
          "x-body-path": [
            "address",
            "line1"
          ]
        },
        "address.name": {
          type: "string",
          minLength: 1,
          "x-flag": "address.name",
          "x-in": "body",
          "x-wire-name": "address.name",
          "x-body-path": [
            "address",
            "name"
          ]
        },
        "address.postal-code": {
          type: "string",
          "x-flag": "address.postal-code",
          "x-in": "body",
          "x-wire-name": "address.postal_code",
          "x-body-path": [
            "address",
            "postal_code"
          ]
        },
        "window.ends-at": {
          format: "date-time",
          type: "string",
          "x-flag": "window.ends-at",
          "x-in": "body",
          "x-wire-name": "window.ends_at",
          "x-body-path": [
            "window",
            "ends_at"
          ]
        },
        "window.starts-at": {
          format: "date-time",
          type: "string",
          "x-flag": "window.starts-at",
          "x-in": "body",
          "x-wire-name": "window.starts_at",
          "x-body-path": [
            "window",
            "starts_at"
          ]
        },
        body: {
          $ref: "#/$defs/CreatePickupRequest",
          "x-content-type": "application/json",
          "x-body-escape": true
        }
      },
      "x-http-method": "POST",
      "x-http-path": "/v1/pickups",
      "x-operation-key": "post /v1/pickups",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "idempotency-key",
        "address.city",
        "address.country",
        "address.line1",
        "address.name",
        "address.postal-code",
        "window.ends-at",
        "window.starts-at"
      ],
      $defs: {
        Address: {
          additionalProperties: false,
          properties: {
            city: {
              description: "City (string)",
              type: "string"
            },
            company: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Company"
            },
            country: {
              description: "Country (string)",
              pattern: "^[A-Z]{2}$",
              type: "string"
            },
            line1: {
              description: "Line1 (string)",
              type: "string"
            },
            line2: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Line2"
            },
            name: {
              description: "Name (string)",
              minLength: 1,
              type: "string"
            },
            phone: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Phone"
            },
            postal_code: {
              description: "Postal code (string)",
              type: "string"
            },
            region: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Region"
            }
          },
          required: [
            "city",
            "country",
            "line1",
            "name",
            "postal_code"
          ],
          type: "object"
        },
        CreatePickupRequest: {
          additionalProperties: false,
          properties: {
            address: {
              $ref: "#/$defs/Address"
            },
            notes: {
              allOf: [
                {
                  anyOf: [
                    {
                      not: {
                        type: "string"
                      }
                    },
                    {
                      type: "string",
                      maxLength: 500
                    }
                  ]
                }
              ],
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Notes"
            },
            shipment_ids: {
              description: "Shipment ids (array)",
              items: {
                type: "string"
              },
              maxItems: 100,
              minItems: 1,
              type: "array"
            },
            window: {
              $ref: "#/$defs/PickupWindow"
            }
          },
          required: [
            "address",
            "shipment_ids",
            "window"
          ],
          type: "object"
        },
        PickupWindow: {
          additionalProperties: false,
          properties: {
            ends_at: {
              description: "Ends at (string, date-time)",
              format: "date-time",
              type: "string"
            },
            starts_at: {
              description: "Starts at (string, date-time)",
              format: "date-time",
              type: "string"
            }
          },
          required: [
            "ends_at",
            "starts_at"
          ],
          type: "object"
        }
      }
    },
    validationSchema: {
      $ref: "schemas/post-v1-pickups-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      address: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      created_at: "2026-06-09T00:00:00Z",
      id: "pku_00000000000000000001",
      object: "pickup",
      shipment_ids: [
        "string"
      ],
      status: "canceled",
      window: {
        ends_at: "2026-09-06T12:00:00Z",
        starts_at: "2026-09-06T09:00:00Z"
      }
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"address\": {\n    \"city\": \"Exampleton\",\n    \"company\": \"Northstar Supplies\",\n    \"country\": \"ZZ\",\n    \"line1\": \"14 Fictional Quay\",\n    \"line2\": \"Unit 7\",\n…\n"
    }
  },
  {
    id: "pickups.list",
    operationKey: "get /v1/pickups",
    path: [
      "pickups",
      "list"
    ],
    summary: "List scheduled pickups",
    httpMethod: "GET",
    httpPath: "/v1/pickups",
    params: [
      {
        flag: "cursor",
        wireName: "cursor",
        in: "query",
        required: false,
        type: "string",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      },
      {
        flag: "limit",
        wireName: "limit",
        in: "query",
        required: false,
        type: "integer",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      },
      {
        flag: "scheduled-on",
        wireName: "scheduled_on",
        in: "query",
        required: false,
        type: "string",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "pickups.list (GET /v1/pickups)",
      type: "object",
      additionalProperties: false,
      properties: {
        cursor: {
          type: "string",
          minLength: 1,
          "x-flag": "cursor",
          "x-in": "query",
          "x-wire-name": "cursor",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          "x-flag": "limit",
          "x-in": "query",
          "x-wire-name": "limit",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        },
        "scheduled-on": {
          format: "date",
          type: "string",
          "x-flag": "scheduled-on",
          "x-in": "query",
          "x-wire-name": "scheduled_on",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/pickups",
      "x-operation-key": "get /v1/pickups",
      "x-deprecated": false,
      "x-paginated": true,
      "x-pagination": {
        scheme: "cursor_page",
        type: "cursor",
        request: [
          {
            role: "cursor",
            location: "query",
            wireName: "cursor",
            flag: "cursor"
          },
          {
            role: "limit",
            location: "query",
            wireName: "limit",
            flag: "limit"
          }
        ],
        response: [
          {
            role: "items",
            pointer: [
              "data"
            ],
            pointerPath: "$.data"
          },
          {
            role: "next_cursor",
            pointer: [
              "next_cursor"
            ],
            pointerPath: "$.next_cursor"
          }
        ],
        termination: "empty-items-or-null-cursor"
      },
      "x-streaming": false,
      "x-max-items": true,
      "x-drain": {
        flag: "max-items",
        scheme: "cursor_page",
        type: "cursor",
        termination: "empty-items-or-null-cursor"
      }
    },
    validationSchema: {
      $ref: "schemas/get-v1-pickups-validation.json"
    },
    paginated: true,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      data: [
        {
          address: {
            city: "Exampleton",
            company: "Northstar Supplies",
            country: "ZZ",
            line1: "14 Fictional Quay",
            line2: "Unit 7",
            name: "Rowan Example",
            phone: "+00000000000",
            postal_code: "EX4 2PL",
            region: "Test Province"
          },
          created_at: "2026-06-09T00:00:00Z",
          id: "pku_00000000000000000001",
          object: "pickup",
          shipment_ids: [
            "string"
          ],
          status: "canceled",
          window: {
            ends_at: "2026-09-06T12:00:00Z",
            starts_at: "2026-09-06T09:00:00Z"
          }
        }
      ],
      has_more: true,
      next_cursor: "string"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"data\": [\n    {\n      \"address\": {\n        \"city\": \"Exampleton\",\n        \"company\": \"Northstar Supplies\",\n        \"country\": \"ZZ\",\n…\n"
    }
  },
  {
    id: "pickups.retrieve",
    operationKey: "get /v1/pickups/{}",
    path: [
      "pickups",
      "retrieve"
    ],
    summary: "Retrieve a pickup",
    httpMethod: "GET",
    httpPath: "/v1/pickups/{pickup_id}",
    params: [
      {
        flag: "pickup-id",
        wireName: "pickup_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "pickups.retrieve (GET /v1/pickups/{pickup_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "pickup-id": {
          type: "string",
          pattern: "^pku_[a-z0-9]{20}$",
          "x-flag": "pickup-id",
          "x-in": "path",
          "x-wire-name": "pickup_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/pickups/{pickup_id}",
      "x-operation-key": "get /v1/pickups/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "pickup-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/get-v1-pickups-validation-2.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      address: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      created_at: "2026-06-09T00:00:00Z",
      id: "pku_00000000000000000001",
      object: "pickup",
      shipment_ids: [
        "string"
      ],
      status: "canceled",
      window: {
        ends_at: "2026-09-06T12:00:00Z",
        starts_at: "2026-09-06T09:00:00Z"
      }
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"address\": {\n    \"city\": \"Exampleton\",\n    \"company\": \"Northstar Supplies\",\n    \"country\": \"ZZ\",\n    \"line1\": \"14 Fictional Quay\",\n    \"line2\": \"Unit 7\",\n…\n"
    }
  }
] as const as unknown as readonly CliCommandSpec[];
