// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from '../core/model.js';

export const RATES_COMMANDS: readonly CliCommandSpec[] = [
  {
    id: "rates.quote",
    operationKey: "post /v1/rates/quote",
    path: [
      "rates",
      "quote"
    ],
    summary: "Quote available shipping services",
    httpMethod: "POST",
    httpPath: "/v1/rates/quote",
    params: [
      {
        flag: "recipient.city",
        wireName: "recipient.city",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "city"
        ]
      },
      {
        flag: "recipient.country",
        wireName: "recipient.country",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "country"
        ]
      },
      {
        flag: "recipient.line1",
        wireName: "recipient.line1",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "line1"
        ]
      },
      {
        flag: "recipient.name",
        wireName: "recipient.name",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "name"
        ]
      },
      {
        flag: "recipient.postal-code",
        wireName: "recipient.postal_code",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "postal_code"
        ]
      },
      {
        flag: "sender.city",
        wireName: "sender.city",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "city"
        ]
      },
      {
        flag: "sender.country",
        wireName: "sender.country",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "country"
        ]
      },
      {
        flag: "sender.line1",
        wireName: "sender.line1",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "line1"
        ]
      },
      {
        flag: "sender.name",
        wireName: "sender.name",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "name"
        ]
      },
      {
        flag: "sender.postal-code",
        wireName: "sender.postal_code",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "postal_code"
        ]
      }
    ],
    body: {
      required: true,
      contentType: "application/json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "rates.quote (POST /v1/rates/quote)",
      type: "object",
      additionalProperties: false,
      properties: {
        "recipient.city": {
          type: "string",
          "x-flag": "recipient.city",
          "x-in": "body",
          "x-wire-name": "recipient.city",
          "x-body-path": [
            "recipient",
            "city"
          ]
        },
        "recipient.country": {
          type: "string",
          pattern: "^[A-Z]{2}$",
          "x-flag": "recipient.country",
          "x-in": "body",
          "x-wire-name": "recipient.country",
          "x-body-path": [
            "recipient",
            "country"
          ]
        },
        "recipient.line1": {
          type: "string",
          "x-flag": "recipient.line1",
          "x-in": "body",
          "x-wire-name": "recipient.line1",
          "x-body-path": [
            "recipient",
            "line1"
          ]
        },
        "recipient.name": {
          type: "string",
          minLength: 1,
          "x-flag": "recipient.name",
          "x-in": "body",
          "x-wire-name": "recipient.name",
          "x-body-path": [
            "recipient",
            "name"
          ]
        },
        "recipient.postal-code": {
          type: "string",
          "x-flag": "recipient.postal-code",
          "x-in": "body",
          "x-wire-name": "recipient.postal_code",
          "x-body-path": [
            "recipient",
            "postal_code"
          ]
        },
        "sender.city": {
          type: "string",
          "x-flag": "sender.city",
          "x-in": "body",
          "x-wire-name": "sender.city",
          "x-body-path": [
            "sender",
            "city"
          ]
        },
        "sender.country": {
          type: "string",
          pattern: "^[A-Z]{2}$",
          "x-flag": "sender.country",
          "x-in": "body",
          "x-wire-name": "sender.country",
          "x-body-path": [
            "sender",
            "country"
          ]
        },
        "sender.line1": {
          type: "string",
          "x-flag": "sender.line1",
          "x-in": "body",
          "x-wire-name": "sender.line1",
          "x-body-path": [
            "sender",
            "line1"
          ]
        },
        "sender.name": {
          type: "string",
          minLength: 1,
          "x-flag": "sender.name",
          "x-in": "body",
          "x-wire-name": "sender.name",
          "x-body-path": [
            "sender",
            "name"
          ]
        },
        "sender.postal-code": {
          type: "string",
          "x-flag": "sender.postal-code",
          "x-in": "body",
          "x-wire-name": "sender.postal_code",
          "x-body-path": [
            "sender",
            "postal_code"
          ]
        },
        body: {
          $ref: "#/$defs/RateQuoteRequest",
          "x-content-type": "application/json",
          "x-body-escape": true
        }
      },
      "x-http-method": "POST",
      "x-http-path": "/v1/rates/quote",
      "x-operation-key": "post /v1/rates/quote",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "recipient.city",
        "recipient.country",
        "recipient.line1",
        "recipient.name",
        "recipient.postal-code",
        "sender.city",
        "sender.country",
        "sender.line1",
        "sender.name",
        "sender.postal-code"
      ],
      $defs: {
        Address: {
          additionalProperties: false,
          properties: {
            city: {
              description: "City (string)",
              type: "string"
            },
            company: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Company"
            },
            country: {
              description: "Country (string)",
              pattern: "^[A-Z]{2}$",
              type: "string"
            },
            line1: {
              description: "Line1 (string)",
              type: "string"
            },
            line2: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Line2"
            },
            name: {
              description: "Name (string)",
              minLength: 1,
              type: "string"
            },
            phone: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Phone"
            },
            postal_code: {
              description: "Postal code (string)",
              type: "string"
            },
            region: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Region"
            }
          },
          required: [
            "city",
            "country",
            "line1",
            "name",
            "postal_code"
          ],
          type: "object"
        },
        Money: {
          additionalProperties: false,
          properties: {
            amount: {
              description: "Amount (string)",
              pattern: "^[0-9]+(\\.[0-9]{2})$",
              type: "string"
            },
            currency: {
              description: "Currency (string)",
              pattern: "^[A-Z]{3}$",
              type: "string"
            }
          },
          required: [
            "amount",
            "currency"
          ],
          type: "object"
        },
        Parcel: {
          additionalProperties: false,
          properties: {
            contents: {
              description: "Contents (array)",
              items: {
                $ref: "#/$defs/ParcelItem"
              },
              maxItems: 50,
              type: "array"
            },
            height_cm: {
              description: "Height cm (number)",
              exclusiveMinimum: 0,
              type: "number"
            },
            length_cm: {
              description: "Length cm (number)",
              exclusiveMinimum: 0,
              type: "number"
            },
            weight_grams: {
              description: "Weight grams (integer)",
              minimum: 1,
              type: "integer"
            },
            width_cm: {
              description: "Width cm (number)",
              exclusiveMinimum: 0,
              type: "number"
            }
          },
          required: [
            "height_cm",
            "length_cm",
            "weight_grams",
            "width_cm"
          ],
          type: "object"
        },
        ParcelItem: {
          additionalProperties: false,
          properties: {
            customs_code: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Customs code"
            },
            description: {
              description: "Description (string)",
              type: "string"
            },
            quantity: {
              description: "Quantity (integer)",
              minimum: 1,
              type: "integer"
            },
            unit_value: {
              $ref: "#/$defs/Money"
            }
          },
          required: [
            "description",
            "quantity",
            "unit_value"
          ],
          type: "object"
        },
        RateQuoteRequest: {
          additionalProperties: false,
          properties: {
            parcels: {
              description: "Parcels (array)",
              items: {
                $ref: "#/$defs/Parcel"
              },
              minItems: 1,
              type: "array"
            },
            recipient: {
              $ref: "#/$defs/Address"
            },
            sender: {
              $ref: "#/$defs/Address"
            }
          },
          required: [
            "parcels",
            "recipient",
            "sender"
          ],
          type: "object"
        }
      }
    },
    validationSchema: {
      $ref: "schemas/post-v1-rates-quote-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      data: [
        {
          amount: {
            amount: "0.00",
            currency: "AAA"
          },
          carrier: "string",
          estimated_delivery_date: "2024-01-01",
          expires_at: "2024-01-01T00:00:00Z",
          id: "string",
          service: "string"
        }
      ]
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"data\": [\n    {\n      \"amount\": {\n        \"amount\": \"0.00\",\n        \"currency\": \"AAA\"\n      },\n…\n"
    }
  }
] as const as unknown as readonly CliCommandSpec[];
