// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from '../core/model.js';

export const RETRIEVE_COMMANDS: readonly CliCommandSpec[] = [
  {
    id: "tracking.retrieve",
    operationKey: "get /v1/tracking/{}",
    path: [
      "retrieve"
    ],
    summary: "Retrieve a public tracking timeline",
    httpMethod: "GET",
    httpPath: "/v1/tracking/{tracking_number}",
    params: [
      {
        flag: "tracking-number",
        wireName: "tracking_number",
        in: "path",
        required: true,
        type: "string"
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "tracking.retrieve (GET /v1/tracking/{tracking_number})",
      type: "object",
      additionalProperties: false,
      properties: {
        "tracking-number": {
          type: "string",
          "x-flag": "tracking-number",
          "x-in": "path",
          "x-wire-name": "tracking_number"
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/tracking/{tracking_number}",
      "x-operation-key": "get /v1/tracking/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "tracking-number"
      ]
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      events: [
        {
          id: "evt_00000000000000000001",
          location: {
            city: "Samplehaven",
            country: "ZZ"
          },
          message: "Parcel scanned at synthetic sorting hub",
          object: "tracking_event",
          occurred_at: "2026-09-05T05:40:00Z",
          shipment_id: "shp_00000000000000000001",
          status: "canceled"
        }
      ],
      shipment: {
        created_at: "2026-09-04T08:15:30Z",
        delivery_instructions: "string",
        id: "shp_00000000000000000001",
        metadata: {
          additionalProp1: "string"
        },
        object: "shipment",
        parcels: [
          {
            contents: "…",
            height_cm: 12,
            length_cm: 30.5,
            weight_grams: 1750,
            width_cm: 20
          }
        ],
        recipient: {
          city: "Exampleton",
          company: "Northstar Supplies",
          country: "ZZ",
          line1: "14 Fictional Quay",
          line2: "Unit 7",
          name: "Rowan Example",
          phone: "+00000000000",
          postal_code: "EX4 2PL",
          region: "Test Province"
        },
        reference: "synthetic-order-1042",
        sender: {
          city: "Exampleton",
          company: "Northstar Supplies",
          country: "ZZ",
          line1: "14 Fictional Quay",
          line2: "Unit 7",
          name: "Rowan Example",
          phone: "+00000000000",
          postal_code: "EX4 2PL",
          region: "Test Province"
        },
        service: "economy",
        status: "canceled",
        tracking_number: "PE-000000000001",
        updated_at: "2026-09-04T08:16:12Z"
      }
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"events\": [\n    {\n      \"id\": \"evt_00000000000000000001\",\n      \"location\": {\n        \"city\": \"Samplehaven\",\n        \"country\": \"ZZ\"\n…\n"
    },
    authAnyOf: []
  }
] as const as unknown as readonly CliCommandSpec[];
