// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from '../core/model.js';

export const SHIPMENTS_COMMANDS: readonly CliCommandSpec[] = [
  {
    id: "shipments.cancel",
    operationKey: "delete /v1/shipments/{}",
    path: [
      "shipments",
      "cancel"
    ],
    summary: "Cancel a shipment before handoff",
    httpMethod: "DELETE",
    httpPath: "/v1/shipments/{shipment_id}",
    params: [
      {
        flag: "shipment-id",
        wireName: "shipment_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "shipments.cancel (DELETE /v1/shipments/{shipment_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "shipment-id": {
          type: "string",
          pattern: "^shp_[a-z0-9]{20}$",
          "x-flag": "shipment-id",
          "x-in": "path",
          "x-wire-name": "shipment_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        }
      },
      "x-http-method": "DELETE",
      "x-http-path": "/v1/shipments/{shipment_id}",
      "x-operation-key": "delete /v1/shipments/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "shipment-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/delete-v1-shipments-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      ok: true
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"ok\": true\n}\n"
    }
  },
  {
    id: "shipments.create",
    operationKey: "post /v1/shipments",
    path: [
      "shipments",
      "create"
    ],
    summary: "Create a shipment",
    httpMethod: "POST",
    httpPath: "/v1/shipments",
    params: [
      {
        flag: "idempotency-key",
        wireName: "Idempotency-Key",
        in: "header",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      },
      {
        flag: "recipient.city",
        wireName: "recipient.city",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "city"
        ]
      },
      {
        flag: "recipient.country",
        wireName: "recipient.country",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "country"
        ]
      },
      {
        flag: "recipient.line1",
        wireName: "recipient.line1",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "line1"
        ]
      },
      {
        flag: "recipient.name",
        wireName: "recipient.name",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "name"
        ]
      },
      {
        flag: "recipient.postal-code",
        wireName: "recipient.postal_code",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "recipient",
          "postal_code"
        ]
      },
      {
        flag: "reference",
        wireName: "reference",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "reference"
        ]
      },
      {
        flag: "sender.city",
        wireName: "sender.city",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "city"
        ]
      },
      {
        flag: "sender.country",
        wireName: "sender.country",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "country"
        ]
      },
      {
        flag: "sender.line1",
        wireName: "sender.line1",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "line1"
        ]
      },
      {
        flag: "sender.name",
        wireName: "sender.name",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "name"
        ]
      },
      {
        flag: "sender.postal-code",
        wireName: "sender.postal_code",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "sender",
          "postal_code"
        ]
      },
      {
        flag: "service",
        wireName: "service",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "service"
        ]
      }
    ],
    body: {
      required: true,
      contentType: "application/json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "shipments.create (POST /v1/shipments)",
      type: "object",
      additionalProperties: false,
      properties: {
        "idempotency-key": {
          format: "uuid",
          type: "string",
          "x-flag": "idempotency-key",
          "x-in": "header",
          "x-wire-name": "Idempotency-Key",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        },
        "recipient.city": {
          type: "string",
          "x-flag": "recipient.city",
          "x-in": "body",
          "x-wire-name": "recipient.city",
          "x-body-path": [
            "recipient",
            "city"
          ]
        },
        "recipient.country": {
          type: "string",
          pattern: "^[A-Z]{2}$",
          "x-flag": "recipient.country",
          "x-in": "body",
          "x-wire-name": "recipient.country",
          "x-body-path": [
            "recipient",
            "country"
          ]
        },
        "recipient.line1": {
          type: "string",
          "x-flag": "recipient.line1",
          "x-in": "body",
          "x-wire-name": "recipient.line1",
          "x-body-path": [
            "recipient",
            "line1"
          ]
        },
        "recipient.name": {
          type: "string",
          minLength: 1,
          "x-flag": "recipient.name",
          "x-in": "body",
          "x-wire-name": "recipient.name",
          "x-body-path": [
            "recipient",
            "name"
          ]
        },
        "recipient.postal-code": {
          type: "string",
          "x-flag": "recipient.postal-code",
          "x-in": "body",
          "x-wire-name": "recipient.postal_code",
          "x-body-path": [
            "recipient",
            "postal_code"
          ]
        },
        reference: {
          type: "string",
          maxLength: 80,
          "x-flag": "reference",
          "x-in": "body",
          "x-wire-name": "reference",
          "x-body-path": [
            "reference"
          ]
        },
        "sender.city": {
          type: "string",
          "x-flag": "sender.city",
          "x-in": "body",
          "x-wire-name": "sender.city",
          "x-body-path": [
            "sender",
            "city"
          ]
        },
        "sender.country": {
          type: "string",
          pattern: "^[A-Z]{2}$",
          "x-flag": "sender.country",
          "x-in": "body",
          "x-wire-name": "sender.country",
          "x-body-path": [
            "sender",
            "country"
          ]
        },
        "sender.line1": {
          type: "string",
          "x-flag": "sender.line1",
          "x-in": "body",
          "x-wire-name": "sender.line1",
          "x-body-path": [
            "sender",
            "line1"
          ]
        },
        "sender.name": {
          type: "string",
          minLength: 1,
          "x-flag": "sender.name",
          "x-in": "body",
          "x-wire-name": "sender.name",
          "x-body-path": [
            "sender",
            "name"
          ]
        },
        "sender.postal-code": {
          type: "string",
          "x-flag": "sender.postal-code",
          "x-in": "body",
          "x-wire-name": "sender.postal_code",
          "x-body-path": [
            "sender",
            "postal_code"
          ]
        },
        service: {
          enum: [
            "economy",
            "express",
            "same_day"
          ],
          type: "string",
          "x-flag": "service",
          "x-in": "body",
          "x-wire-name": "service",
          "x-body-path": [
            "service"
          ]
        },
        body: {
          $ref: "#/$defs/CreateShipmentRequest",
          "x-content-type": "application/json",
          "x-body-escape": true
        }
      },
      "x-http-method": "POST",
      "x-http-path": "/v1/shipments",
      "x-operation-key": "post /v1/shipments",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "idempotency-key",
        "recipient.city",
        "recipient.country",
        "recipient.line1",
        "recipient.name",
        "recipient.postal-code",
        "reference",
        "sender.city",
        "sender.country",
        "sender.line1",
        "sender.name",
        "sender.postal-code",
        "service"
      ],
      $defs: {
        Address: {
          additionalProperties: false,
          properties: {
            city: {
              description: "City (string)",
              type: "string"
            },
            company: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Company"
            },
            country: {
              description: "Country (string)",
              pattern: "^[A-Z]{2}$",
              type: "string"
            },
            line1: {
              description: "Line1 (string)",
              type: "string"
            },
            line2: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Line2"
            },
            name: {
              description: "Name (string)",
              minLength: 1,
              type: "string"
            },
            phone: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Phone"
            },
            postal_code: {
              description: "Postal code (string)",
              type: "string"
            },
            region: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Region"
            }
          },
          required: [
            "city",
            "country",
            "line1",
            "name",
            "postal_code"
          ],
          type: "object"
        },
        CreateShipmentRequest: {
          additionalProperties: false,
          properties: {
            delivery_instructions: {
              allOf: [
                {
                  anyOf: [
                    {
                      not: {
                        type: "string"
                      }
                    },
                    {
                      type: "string",
                      maxLength: 500
                    }
                  ]
                }
              ],
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Delivery instructions"
            },
            metadata: {
              additionalProperties: {
                type: "string"
              },
              description: "Metadata (object)",
              maxProperties: 20,
              type: "object"
            },
            parcels: {
              description: "Parcels (array)",
              items: {
                $ref: "#/$defs/Parcel"
              },
              maxItems: 20,
              minItems: 1,
              type: "array"
            },
            recipient: {
              $ref: "#/$defs/Address"
            },
            reference: {
              description: "Reference (string)",
              maxLength: 80,
              type: "string"
            },
            sender: {
              $ref: "#/$defs/Address"
            },
            service: {
              description: "Service (string; one of \"economy\", \"express\", \"same_day\")",
              enum: [
                "economy",
                "express",
                "same_day"
              ],
              type: "string"
            }
          },
          required: [
            "parcels",
            "recipient",
            "reference",
            "sender",
            "service"
          ],
          type: "object"
        },
        Money: {
          additionalProperties: false,
          properties: {
            amount: {
              description: "Amount (string)",
              pattern: "^[0-9]+(\\.[0-9]{2})$",
              type: "string"
            },
            currency: {
              description: "Currency (string)",
              pattern: "^[A-Z]{3}$",
              type: "string"
            }
          },
          required: [
            "amount",
            "currency"
          ],
          type: "object"
        },
        Parcel: {
          additionalProperties: false,
          properties: {
            contents: {
              description: "Contents (array)",
              items: {
                $ref: "#/$defs/ParcelItem"
              },
              maxItems: 50,
              type: "array"
            },
            height_cm: {
              description: "Height cm (number)",
              exclusiveMinimum: 0,
              type: "number"
            },
            length_cm: {
              description: "Length cm (number)",
              exclusiveMinimum: 0,
              type: "number"
            },
            weight_grams: {
              description: "Weight grams (integer)",
              minimum: 1,
              type: "integer"
            },
            width_cm: {
              description: "Width cm (number)",
              exclusiveMinimum: 0,
              type: "number"
            }
          },
          required: [
            "height_cm",
            "length_cm",
            "weight_grams",
            "width_cm"
          ],
          type: "object"
        },
        ParcelItem: {
          additionalProperties: false,
          properties: {
            customs_code: {
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Customs code"
            },
            description: {
              description: "Description (string)",
              type: "string"
            },
            quantity: {
              description: "Quantity (integer)",
              minimum: 1,
              type: "integer"
            },
            unit_value: {
              $ref: "#/$defs/Money"
            }
          },
          required: [
            "description",
            "quantity",
            "unit_value"
          ],
          type: "object"
        }
      }
    },
    validationSchema: {
      $ref: "schemas/post-v1-shipments-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      created_at: "2026-09-04T08:15:30Z",
      delivery_instructions: "string",
      id: "shp_00000000000000000001",
      metadata: {
        additionalProp1: "string"
      },
      object: "shipment",
      parcels: [
        {
          contents: [
            "…"
          ],
          height_cm: 12,
          length_cm: 30.5,
          weight_grams: 1750,
          width_cm: 20
        }
      ],
      recipient: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      reference: "synthetic-order-1042",
      sender: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      service: "economy",
      status: "canceled",
      tracking_number: "PE-000000000001",
      updated_at: "2026-09-04T08:16:12Z"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"created_at\": \"2026-09-04T08:15:30Z\",\n  \"delivery_instructions\": \"string\",\n  \"id\": \"shp_00000000000000000001\",\n  \"metadata\": {\n    \"additionalProp1\": \"string\"\n  },\n…\n"
    }
  },
  {
    id: "shipments.events.list",
    operationKey: "get /v1/shipments/{}/events",
    path: [
      "shipments",
      "events",
      "list"
    ],
    summary: "List tracking events for a shipment",
    httpMethod: "GET",
    httpPath: "/v1/shipments/{shipment_id}/events",
    params: [
      {
        flag: "shipment-id",
        wireName: "shipment_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      },
      {
        flag: "cursor",
        wireName: "cursor",
        in: "query",
        required: false,
        type: "string",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      },
      {
        flag: "limit",
        wireName: "limit",
        in: "query",
        required: false,
        type: "integer",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "shipments.events.list (GET /v1/shipments/{shipment_id}/events)",
      type: "object",
      additionalProperties: false,
      properties: {
        "shipment-id": {
          type: "string",
          pattern: "^shp_[a-z0-9]{20}$",
          "x-flag": "shipment-id",
          "x-in": "path",
          "x-wire-name": "shipment_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        },
        cursor: {
          type: "string",
          minLength: 1,
          "x-flag": "cursor",
          "x-in": "query",
          "x-wire-name": "cursor",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          "x-flag": "limit",
          "x-in": "query",
          "x-wire-name": "limit",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/shipments/{shipment_id}/events",
      "x-operation-key": "get /v1/shipments/{}/events",
      "x-deprecated": false,
      "x-paginated": true,
      "x-pagination": {
        scheme: "cursor_page",
        type: "cursor",
        request: [
          {
            role: "cursor",
            location: "query",
            wireName: "cursor",
            flag: "cursor"
          },
          {
            role: "limit",
            location: "query",
            wireName: "limit",
            flag: "limit"
          }
        ],
        response: [
          {
            role: "items",
            pointer: [
              "data"
            ],
            pointerPath: "$.data"
          },
          {
            role: "next_cursor",
            pointer: [
              "next_cursor"
            ],
            pointerPath: "$.next_cursor"
          }
        ],
        termination: "empty-items-or-null-cursor"
      },
      "x-streaming": false,
      "x-max-items": true,
      "x-drain": {
        flag: "max-items",
        scheme: "cursor_page",
        type: "cursor",
        termination: "empty-items-or-null-cursor"
      },
      required: [
        "shipment-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/get-v1-shipments-events-validation.json"
    },
    paginated: true,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      data: [
        {
          id: "evt_00000000000000000001",
          location: {
            city: "Samplehaven",
            country: "ZZ"
          },
          message: "Parcel scanned at synthetic sorting hub",
          object: "tracking_event",
          occurred_at: "2026-09-05T05:40:00Z",
          shipment_id: "shp_00000000000000000001",
          status: "canceled"
        }
      ],
      has_more: true,
      next_cursor: "string"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"data\": [\n    {\n      \"id\": \"evt_00000000000000000001\",\n      \"location\": {\n        \"city\": \"Samplehaven\",\n        \"country\": \"ZZ\"\n…\n"
    }
  },
  {
    id: "shipments.list",
    operationKey: "get /v1/shipments",
    path: [
      "shipments",
      "list"
    ],
    summary: "List shipments",
    httpMethod: "GET",
    httpPath: "/v1/shipments",
    params: [
      {
        flag: "cursor",
        wireName: "cursor",
        in: "query",
        required: false,
        type: "string",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      },
      {
        flag: "limit",
        wireName: "limit",
        in: "query",
        required: false,
        type: "integer",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      },
      {
        flag: "status",
        wireName: "status",
        in: "query",
        required: false,
        type: "json",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "shipments.list (GET /v1/shipments)",
      type: "object",
      additionalProperties: false,
      properties: {
        cursor: {
          type: "string",
          minLength: 1,
          "x-flag": "cursor",
          "x-in": "query",
          "x-wire-name": "cursor",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          "x-flag": "limit",
          "x-in": "query",
          "x-wire-name": "limit",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        },
        status: {
          $ref: "#/$defs/ShipmentStatus",
          "x-flag": "status",
          "x-in": "query",
          "x-wire-name": "status",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/shipments",
      "x-operation-key": "get /v1/shipments",
      "x-deprecated": false,
      "x-paginated": true,
      "x-pagination": {
        scheme: "cursor_page",
        type: "cursor",
        request: [
          {
            role: "cursor",
            location: "query",
            wireName: "cursor",
            flag: "cursor"
          },
          {
            role: "limit",
            location: "query",
            wireName: "limit",
            flag: "limit"
          }
        ],
        response: [
          {
            role: "items",
            pointer: [
              "data"
            ],
            pointerPath: "$.data"
          },
          {
            role: "next_cursor",
            pointer: [
              "next_cursor"
            ],
            pointerPath: "$.next_cursor"
          }
        ],
        termination: "empty-items-or-null-cursor"
      },
      "x-streaming": false,
      "x-max-items": true,
      "x-drain": {
        flag: "max-items",
        scheme: "cursor_page",
        type: "cursor",
        termination: "empty-items-or-null-cursor"
      },
      $defs: {
        ShipmentStatus: {
          enum: [
            "draft",
            "label_purchased",
            "in_transit",
            "out_for_delivery",
            "delivered",
            "exception",
            "canceled"
          ],
          type: "string"
        }
      }
    },
    validationSchema: {
      $ref: "schemas/get-v1-shipments-validation.json"
    },
    paginated: true,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      data: [
        {
          created_at: "2026-09-04T08:15:30Z",
          delivery_instructions: "string",
          id: "shp_00000000000000000001",
          metadata: {
            additionalProp1: "string"
          },
          object: "shipment",
          parcels: [
            "…"
          ],
          recipient: {
            city: "Exampleton",
            company: "Northstar Supplies",
            country: "ZZ",
            line1: "14 Fictional Quay",
            line2: "Unit 7",
            name: "Rowan Example",
            phone: "+00000000000",
            postal_code: "EX4 2PL",
            region: "Test Province"
          },
          reference: "synthetic-order-1042",
          sender: {
            city: "Exampleton",
            company: "Northstar Supplies",
            country: "ZZ",
            line1: "14 Fictional Quay",
            line2: "Unit 7",
            name: "Rowan Example",
            phone: "+00000000000",
            postal_code: "EX4 2PL",
            region: "Test Province"
          },
          service: "economy",
          status: "canceled",
          tracking_number: "PE-000000000001",
          updated_at: "2026-09-04T08:16:12Z"
        }
      ],
      has_more: true,
      next_cursor: "string"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"data\": [\n    {\n      \"created_at\": \"2026-09-04T08:15:30Z\",\n      \"delivery_instructions\": \"string\",\n      \"id\": \"shp_00000000000000000001\",\n      \"metadata\": {\n…\n"
    }
  },
  {
    id: "shipments.retrieve",
    operationKey: "get /v1/shipments/{}",
    path: [
      "shipments",
      "retrieve"
    ],
    summary: "Retrieve a shipment",
    httpMethod: "GET",
    httpPath: "/v1/shipments/{shipment_id}",
    params: [
      {
        flag: "shipment-id",
        wireName: "shipment_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "shipments.retrieve (GET /v1/shipments/{shipment_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "shipment-id": {
          type: "string",
          pattern: "^shp_[a-z0-9]{20}$",
          "x-flag": "shipment-id",
          "x-in": "path",
          "x-wire-name": "shipment_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/shipments/{shipment_id}",
      "x-operation-key": "get /v1/shipments/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "shipment-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/get-v1-shipments-validation-2.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      created_at: "2026-09-04T08:15:30Z",
      delivery_instructions: "string",
      id: "shp_00000000000000000001",
      metadata: {
        additionalProp1: "string"
      },
      object: "shipment",
      parcels: [
        {
          contents: [
            "…"
          ],
          height_cm: 12,
          length_cm: 30.5,
          weight_grams: 1750,
          width_cm: 20
        }
      ],
      recipient: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      reference: "synthetic-order-1042",
      sender: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      service: "economy",
      status: "canceled",
      tracking_number: "PE-000000000001",
      updated_at: "2026-09-04T08:16:12Z"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"created_at\": \"2026-09-04T08:15:30Z\",\n  \"delivery_instructions\": \"string\",\n  \"id\": \"shp_00000000000000000001\",\n  \"metadata\": {\n    \"additionalProp1\": \"string\"\n  },\n…\n"
    }
  },
  {
    id: "shipments.update",
    operationKey: "patch /v1/shipments/{}",
    path: [
      "shipments",
      "update"
    ],
    summary: "Update delivery instructions",
    httpMethod: "PATCH",
    httpPath: "/v1/shipments/{shipment_id}",
    params: [
      {
        flag: "shipment-id",
        wireName: "shipment_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: {
      required: true,
      contentType: "application/merge-patch+json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "shipments.update (PATCH /v1/shipments/{shipment_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "shipment-id": {
          type: "string",
          pattern: "^shp_[a-z0-9]{20}$",
          "x-flag": "shipment-id",
          "x-in": "path",
          "x-wire-name": "shipment_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        },
        body: {
          $ref: "#/$defs/UpdateShipmentRequest",
          "x-content-type": "application/merge-patch+json",
          "x-body-escape": true
        }
      },
      "x-http-method": "PATCH",
      "x-http-path": "/v1/shipments/{shipment_id}",
      "x-operation-key": "patch /v1/shipments/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "shipment-id",
        "body"
      ],
      $defs: {
        UpdateShipmentRequest: {
          additionalProperties: false,
          properties: {
            delivery_instructions: {
              allOf: [
                {
                  anyOf: [
                    {
                      not: {
                        type: "string"
                      }
                    },
                    {
                      type: "string",
                      maxLength: 500
                    }
                  ]
                }
              ],
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Delivery instructions"
            },
            metadata: {
              additionalProperties: {
                type: "string"
              },
              description: "Metadata (object)",
              type: "object"
            }
          },
          type: "object",
          minProperties: 1
        }
      }
    },
    validationSchema: {
      $ref: "schemas/patch-v1-shipments-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      created_at: "2026-09-04T08:15:30Z",
      delivery_instructions: "string",
      id: "shp_00000000000000000001",
      metadata: {
        additionalProp1: "string"
      },
      object: "shipment",
      parcels: [
        {
          contents: [
            "…"
          ],
          height_cm: 12,
          length_cm: 30.5,
          weight_grams: 1750,
          width_cm: 20
        }
      ],
      recipient: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      reference: "synthetic-order-1042",
      sender: {
        city: "Exampleton",
        company: "Northstar Supplies",
        country: "ZZ",
        line1: "14 Fictional Quay",
        line2: "Unit 7",
        name: "Rowan Example",
        phone: "+00000000000",
        postal_code: "EX4 2PL",
        region: "Test Province"
      },
      service: "economy",
      status: "canceled",
      tracking_number: "PE-000000000001",
      updated_at: "2026-09-04T08:16:12Z"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"created_at\": \"2026-09-04T08:15:30Z\",\n  \"delivery_instructions\": \"string\",\n  \"id\": \"shp_00000000000000000001\",\n  \"metadata\": {\n    \"additionalProp1\": \"string\"\n  },\n…\n"
    }
  }
] as const as unknown as readonly CliCommandSpec[];
