// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from '../core/model.js';

export const WEBHOOK_ENDPOINTS_COMMANDS: readonly CliCommandSpec[] = [
  {
    id: "webhook_endpoints.create",
    operationKey: "post /v1/webhook-endpoints",
    path: [
      "webhook-endpoints",
      "create"
    ],
    summary: "Register a webhook endpoint",
    httpMethod: "POST",
    httpPath: "/v1/webhook-endpoints",
    params: [
      {
        flag: "url",
        wireName: "url",
        in: "body",
        required: true,
        type: "string",
        bodyPath: [
          "url"
        ]
      }
    ],
    body: {
      required: true,
      contentType: "application/json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "webhook_endpoints.create (POST /v1/webhook-endpoints)",
      type: "object",
      additionalProperties: false,
      properties: {
        url: {
          format: "uri",
          type: "string",
          "x-flag": "url",
          "x-in": "body",
          "x-wire-name": "url",
          "x-body-path": [
            "url"
          ]
        },
        body: {
          $ref: "#/$defs/CreateWebhookEndpointRequest",
          "x-content-type": "application/json",
          "x-body-escape": true
        }
      },
      "x-http-method": "POST",
      "x-http-path": "/v1/webhook-endpoints",
      "x-operation-key": "post /v1/webhook-endpoints",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "url"
      ],
      $defs: {
        CreateWebhookEndpointRequest: {
          additionalProperties: false,
          properties: {
            description: {
              allOf: [
                {
                  anyOf: [
                    {
                      not: {
                        type: "string"
                      }
                    },
                    {
                      type: "string",
                      maxLength: 120
                    }
                  ]
                }
              ],
              anyOf: [
                {
                  type: "string"
                },
                {
                  type: "null"
                }
              ],
              description: "Description"
            },
            events: {
              description: "Events (array)",
              items: {
                $ref: "#/$defs/WebhookEventType"
              },
              minItems: 1,
              type: "array",
              uniqueItems: true
            },
            url: {
              description: "Url (string, uri)",
              format: "uri",
              type: "string"
            }
          },
          required: [
            "events",
            "url"
          ],
          type: "object"
        },
        WebhookEventType: {
          enum: [
            "shipment.created",
            "shipment.status_changed",
            "shipment.delivered",
            "shipment.exception",
            "pickup.completed"
          ],
          type: "string"
        }
      }
    },
    validationSchema: {
      $ref: "schemas/post-v1-webhook-endpoints-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      created_at: "2026-06-09T00:00:00Z",
      enabled: true,
      events: [
        "pickup.completed"
      ],
      id: "whe_00000000000000000001",
      object: "webhook_endpoint",
      signing_secret_hint: "synthetic-key-ending-0000",
      url: "https://hooks.parcel-events.example/events"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"created_at\": \"2026-06-09T00:00:00Z\",\n  \"enabled\": true,\n  \"events\": [\n    \"pickup.completed\"\n  ],\n  \"id\": \"whe_00000000000000000001\",\n…\n"
    }
  },
  {
    id: "webhook_endpoints.get",
    operationKey: "get /v1/webhook-endpoints/{}",
    path: [
      "webhook-endpoints",
      "get"
    ],
    summary: "Retrieve a webhook endpoint",
    httpMethod: "GET",
    httpPath: "/v1/webhook-endpoints/{endpoint_id}",
    params: [
      {
        flag: "endpoint-id",
        wireName: "endpoint_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "webhook_endpoints.get (GET /v1/webhook-endpoints/{endpoint_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "endpoint-id": {
          type: "string",
          pattern: "^whe_[a-z0-9]{20}$",
          "x-flag": "endpoint-id",
          "x-in": "path",
          "x-wire-name": "endpoint_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/webhook-endpoints/{endpoint_id}",
      "x-operation-key": "get /v1/webhook-endpoints/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "endpoint-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/get-v1-webhook-endpoints-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      created_at: "2026-06-09T00:00:00Z",
      enabled: true,
      events: [
        "pickup.completed"
      ],
      id: "whe_00000000000000000001",
      object: "webhook_endpoint",
      signing_secret_hint: "synthetic-key-ending-0000",
      url: "https://hooks.parcel-events.example/events"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"created_at\": \"2026-06-09T00:00:00Z\",\n  \"enabled\": true,\n  \"events\": [\n    \"pickup.completed\"\n  ],\n  \"id\": \"whe_00000000000000000001\",\n…\n"
    }
  },
  {
    id: "webhook_endpoints.list",
    operationKey: "get /v1/webhook-endpoints",
    path: [
      "webhook-endpoints",
      "list"
    ],
    summary: "List webhook endpoints",
    httpMethod: "GET",
    httpPath: "/v1/webhook-endpoints",
    params: [
      {
        flag: "cursor",
        wireName: "cursor",
        in: "query",
        required: false,
        type: "string",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      },
      {
        flag: "limit",
        wireName: "limit",
        in: "query",
        required: false,
        type: "integer",
        serialization: {
          style: "form",
          explode: true,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "webhook_endpoints.list (GET /v1/webhook-endpoints)",
      type: "object",
      additionalProperties: false,
      properties: {
        cursor: {
          type: "string",
          minLength: 1,
          "x-flag": "cursor",
          "x-in": "query",
          "x-wire-name": "cursor",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 100,
          "x-flag": "limit",
          "x-in": "query",
          "x-wire-name": "limit",
          "x-serialization": {
            style: "form",
            explode: true,
            allowReserved: false
          }
        }
      },
      "x-http-method": "GET",
      "x-http-path": "/v1/webhook-endpoints",
      "x-operation-key": "get /v1/webhook-endpoints",
      "x-deprecated": false,
      "x-paginated": true,
      "x-pagination": {
        scheme: "cursor_page",
        type: "cursor",
        request: [
          {
            role: "cursor",
            location: "query",
            wireName: "cursor",
            flag: "cursor"
          },
          {
            role: "limit",
            location: "query",
            wireName: "limit",
            flag: "limit"
          }
        ],
        response: [
          {
            role: "items",
            pointer: [
              "data"
            ],
            pointerPath: "$.data"
          },
          {
            role: "next_cursor",
            pointer: [
              "next_cursor"
            ],
            pointerPath: "$.next_cursor"
          }
        ],
        termination: "empty-items-or-null-cursor"
      },
      "x-streaming": false,
      "x-max-items": true,
      "x-drain": {
        flag: "max-items",
        scheme: "cursor_page",
        type: "cursor",
        termination: "empty-items-or-null-cursor"
      }
    },
    validationSchema: {
      $ref: "schemas/get-v1-webhook-endpoints-validation-2.json"
    },
    paginated: true,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      data: [
        {
          created_at: "2026-06-09T00:00:00Z",
          enabled: true,
          events: [
            "pickup.completed"
          ],
          id: "whe_00000000000000000001",
          object: "webhook_endpoint",
          signing_secret_hint: "synthetic-key-ending-0000",
          url: "https://hooks.parcel-events.example/events"
        }
      ],
      has_more: true,
      next_cursor: "string"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"data\": [\n    {\n      \"created_at\": \"2026-06-09T00:00:00Z\",\n      \"enabled\": true,\n      \"events\": [\n        \"pickup.completed\"\n…\n"
    }
  },
  {
    id: "webhook_endpoints.remove",
    operationKey: "delete /v1/webhook-endpoints/{}",
    path: [
      "webhook-endpoints",
      "remove"
    ],
    summary: "Delete a webhook endpoint",
    httpMethod: "DELETE",
    httpPath: "/v1/webhook-endpoints/{endpoint_id}",
    params: [
      {
        flag: "endpoint-id",
        wireName: "endpoint_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: null,
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "webhook_endpoints.remove (DELETE /v1/webhook-endpoints/{endpoint_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "endpoint-id": {
          type: "string",
          pattern: "^whe_[a-z0-9]{20}$",
          "x-flag": "endpoint-id",
          "x-in": "path",
          "x-wire-name": "endpoint_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        }
      },
      "x-http-method": "DELETE",
      "x-http-path": "/v1/webhook-endpoints/{endpoint_id}",
      "x-operation-key": "delete /v1/webhook-endpoints/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "endpoint-id"
      ]
    },
    validationSchema: {
      $ref: "schemas/delete-v1-webhook-endpoints-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      ok: true
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"ok\": true\n}\n"
    }
  },
  {
    id: "webhook_endpoints.update",
    operationKey: "patch /v1/webhook-endpoints/{}",
    path: [
      "webhook-endpoints",
      "update"
    ],
    summary: "Update a webhook endpoint",
    httpMethod: "PATCH",
    httpPath: "/v1/webhook-endpoints/{endpoint_id}",
    params: [
      {
        flag: "endpoint-id",
        wireName: "endpoint_id",
        in: "path",
        required: true,
        type: "string",
        serialization: {
          style: "simple",
          explode: false,
          allowReserved: false
        }
      }
    ],
    body: {
      required: true,
      contentType: "application/merge-patch+json"
    },
    inputSchema: {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title: "webhook_endpoints.update (PATCH /v1/webhook-endpoints/{endpoint_id})",
      type: "object",
      additionalProperties: false,
      properties: {
        "endpoint-id": {
          type: "string",
          pattern: "^whe_[a-z0-9]{20}$",
          "x-flag": "endpoint-id",
          "x-in": "path",
          "x-wire-name": "endpoint_id",
          "x-serialization": {
            style: "simple",
            explode: false,
            allowReserved: false
          }
        },
        body: {
          $ref: "#/$defs/UpdateWebhookEndpointRequest",
          "x-content-type": "application/merge-patch+json",
          "x-body-escape": true
        }
      },
      "x-http-method": "PATCH",
      "x-http-path": "/v1/webhook-endpoints/{endpoint_id}",
      "x-operation-key": "patch /v1/webhook-endpoints/{}",
      "x-deprecated": false,
      "x-paginated": false,
      "x-pagination": null,
      "x-streaming": false,
      required: [
        "endpoint-id",
        "body"
      ],
      $defs: {
        UpdateWebhookEndpointRequest: {
          additionalProperties: false,
          properties: {
            enabled: {
              description: "Enabled (boolean)",
              type: "boolean"
            },
            events: {
              description: "Events (array)",
              items: {
                $ref: "#/$defs/WebhookEventType"
              },
              minItems: 1,
              type: "array",
              uniqueItems: true
            },
            url: {
              description: "Url (string, uri)",
              format: "uri",
              type: "string"
            }
          },
          type: "object",
          minProperties: 1
        },
        WebhookEventType: {
          enum: [
            "shipment.created",
            "shipment.status_changed",
            "shipment.delivered",
            "shipment.exception",
            "pickup.completed"
          ],
          type: "string"
        }
      }
    },
    validationSchema: {
      $ref: "schemas/patch-v1-webhook-endpoints-validation.json"
    },
    paginated: false,
    pagination: null,
    streaming: false,
    stream: null,
    deprecated: false,
    mockResponse: {
      created_at: "2026-06-09T00:00:00Z",
      enabled: true,
      events: [
        "pickup.completed"
      ],
      id: "whe_00000000000000000001",
      object: "webhook_endpoint",
      signing_secret_hint: "synthetic-key-ending-0000",
      url: "https://hooks.parcel-events.example/events"
    },
    example: {
      request: "parcel-events-cli --dry-run\n",
      response: "{\n  \"created_at\": \"2026-06-09T00:00:00Z\",\n  \"enabled\": true,\n  \"events\": [\n    \"pickup.completed\"\n  ],\n  \"id\": \"whe_00000000000000000001\",\n…\n"
    }
  }
] as const as unknown as readonly CliCommandSpec[];
