// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCatalogEntry } from './core/model.js';

export const CATALOG: readonly CliCatalogEntry[] = [
  {
    id: "labels.create",
    operationKey: "post /v1/labels",
    path: [
      "labels",
      "create"
    ],
    httpMethod: "POST",
    httpPath: "/v1/labels",
    flags: [
      "idempotency-key",
      "format-body",
      "shipment-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/labels.ts",
    summary: "Buy and render a shipping label"
  },
  {
    id: "labels.retrieve",
    operationKey: "get /v1/labels/{}",
    path: [
      "labels",
      "retrieve"
    ],
    httpMethod: "GET",
    httpPath: "/v1/labels/{label_id}",
    flags: [
      "label-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/labels.ts",
    summary: "Retrieve label metadata and download URL"
  },
  {
    id: "pickups.cancel",
    operationKey: "delete /v1/pickups/{}",
    path: [
      "pickups",
      "cancel"
    ],
    httpMethod: "DELETE",
    httpPath: "/v1/pickups/{pickup_id}",
    flags: [
      "pickup-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/pickups.ts",
    summary: "Cancel a pickup"
  },
  {
    id: "pickups.create",
    operationKey: "post /v1/pickups",
    path: [
      "pickups",
      "create"
    ],
    httpMethod: "POST",
    httpPath: "/v1/pickups",
    flags: [
      "idempotency-key",
      "address.city",
      "address.country",
      "address.line1",
      "address.name",
      "address.postal-code",
      "window.ends-at",
      "window.starts-at"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/pickups.ts",
    summary: "Schedule a carrier pickup"
  },
  {
    id: "pickups.list",
    operationKey: "get /v1/pickups",
    path: [
      "pickups",
      "list"
    ],
    httpMethod: "GET",
    httpPath: "/v1/pickups",
    flags: [
      "cursor",
      "limit",
      "scheduled-on"
    ],
    paginated: true,
    deprecated: false,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    stream: null,
    shard: "src/commands/pickups.ts",
    summary: "List scheduled pickups"
  },
  {
    id: "pickups.retrieve",
    operationKey: "get /v1/pickups/{}",
    path: [
      "pickups",
      "retrieve"
    ],
    httpMethod: "GET",
    httpPath: "/v1/pickups/{pickup_id}",
    flags: [
      "pickup-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/pickups.ts",
    summary: "Retrieve a pickup"
  },
  {
    id: "rates.quote",
    operationKey: "post /v1/rates/quote",
    path: [
      "rates",
      "quote"
    ],
    httpMethod: "POST",
    httpPath: "/v1/rates/quote",
    flags: [
      "recipient.city",
      "recipient.country",
      "recipient.line1",
      "recipient.name",
      "recipient.postal-code",
      "sender.city",
      "sender.country",
      "sender.line1",
      "sender.name",
      "sender.postal-code"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/rates.ts",
    summary: "Quote available shipping services"
  },
  {
    id: "tracking.retrieve",
    operationKey: "get /v1/tracking/{}",
    path: [
      "retrieve"
    ],
    httpMethod: "GET",
    httpPath: "/v1/tracking/{tracking_number}",
    flags: [
      "tracking-number"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/retrieve.ts",
    summary: "Retrieve a public tracking timeline"
  },
  {
    id: "shipments.cancel",
    operationKey: "delete /v1/shipments/{}",
    path: [
      "shipments",
      "cancel"
    ],
    httpMethod: "DELETE",
    httpPath: "/v1/shipments/{shipment_id}",
    flags: [
      "shipment-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/shipments.ts",
    summary: "Cancel a shipment before handoff"
  },
  {
    id: "shipments.create",
    operationKey: "post /v1/shipments",
    path: [
      "shipments",
      "create"
    ],
    httpMethod: "POST",
    httpPath: "/v1/shipments",
    flags: [
      "idempotency-key",
      "recipient.city",
      "recipient.country",
      "recipient.line1",
      "recipient.name",
      "recipient.postal-code",
      "reference",
      "sender.city",
      "sender.country",
      "sender.line1",
      "sender.name",
      "sender.postal-code",
      "service"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/shipments.ts",
    summary: "Create a shipment"
  },
  {
    id: "shipments.events.list",
    operationKey: "get /v1/shipments/{}/events",
    path: [
      "shipments",
      "events",
      "list"
    ],
    httpMethod: "GET",
    httpPath: "/v1/shipments/{shipment_id}/events",
    flags: [
      "shipment-id",
      "cursor",
      "limit"
    ],
    paginated: true,
    deprecated: false,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    stream: null,
    shard: "src/commands/shipments.ts",
    summary: "List tracking events for a shipment"
  },
  {
    id: "shipments.list",
    operationKey: "get /v1/shipments",
    path: [
      "shipments",
      "list"
    ],
    httpMethod: "GET",
    httpPath: "/v1/shipments",
    flags: [
      "cursor",
      "limit",
      "status"
    ],
    paginated: true,
    deprecated: false,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    stream: null,
    shard: "src/commands/shipments.ts",
    summary: "List shipments"
  },
  {
    id: "shipments.retrieve",
    operationKey: "get /v1/shipments/{}",
    path: [
      "shipments",
      "retrieve"
    ],
    httpMethod: "GET",
    httpPath: "/v1/shipments/{shipment_id}",
    flags: [
      "shipment-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/shipments.ts",
    summary: "Retrieve a shipment"
  },
  {
    id: "shipments.update",
    operationKey: "patch /v1/shipments/{}",
    path: [
      "shipments",
      "update"
    ],
    httpMethod: "PATCH",
    httpPath: "/v1/shipments/{shipment_id}",
    flags: [
      "shipment-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/shipments.ts",
    summary: "Update delivery instructions"
  },
  {
    id: "webhook_endpoints.create",
    operationKey: "post /v1/webhook-endpoints",
    path: [
      "webhook-endpoints",
      "create"
    ],
    httpMethod: "POST",
    httpPath: "/v1/webhook-endpoints",
    flags: [
      "url"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/webhook-endpoints.ts",
    summary: "Register a webhook endpoint"
  },
  {
    id: "webhook_endpoints.list",
    operationKey: "get /v1/webhook-endpoints",
    path: [
      "webhook-endpoints",
      "list"
    ],
    httpMethod: "GET",
    httpPath: "/v1/webhook-endpoints",
    flags: [
      "cursor",
      "limit"
    ],
    paginated: true,
    deprecated: false,
    pagination: {
      scheme: "cursor_page",
      type: "cursor",
      request: [
        {
          role: "cursor",
          location: "query",
          wireName: "cursor"
        },
        {
          role: "limit",
          location: "query",
          wireName: "limit"
        }
      ],
      response: [
        {
          role: "items",
          pointer: [
            "data"
          ]
        },
        {
          role: "next_cursor",
          pointer: [
            "next_cursor"
          ]
        }
      ]
    },
    stream: null,
    shard: "src/commands/webhook-endpoints.ts",
    summary: "List webhook endpoints"
  },
  {
    id: "webhook_endpoints.remove",
    operationKey: "delete /v1/webhook-endpoints/{}",
    path: [
      "webhook-endpoints",
      "remove"
    ],
    httpMethod: "DELETE",
    httpPath: "/v1/webhook-endpoints/{endpoint_id}",
    flags: [
      "endpoint-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/webhook-endpoints.ts",
    summary: "Delete a webhook endpoint"
  },
  {
    id: "webhook_endpoints.update",
    operationKey: "patch /v1/webhook-endpoints/{}",
    path: [
      "webhook-endpoints",
      "update"
    ],
    httpMethod: "PATCH",
    httpPath: "/v1/webhook-endpoints/{endpoint_id}",
    flags: [
      "endpoint-id"
    ],
    paginated: false,
    deprecated: false,
    pagination: null,
    stream: null,
    shard: "src/commands/webhook-endpoints.ts",
    summary: "Update a webhook endpoint"
  }
] as const as unknown as readonly CliCatalogEntry[];
