#!/usr/bin/env node
// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { readFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { runCli } from './core/dispatch.js';
import type { CliIo, CliServeHandle, CliServeOpts } from './core/model.js';
import { CLI_SPEC } from './commands.js';
import { loadCommand } from './load-command.js';

async function readStdin(): Promise<string> {
  const chunks: string[] = [];
  for await (const chunk of process.stdin) chunks.push(String(chunk));
  return chunks.join('');
}

async function serve(opts: CliServeOpts): Promise<CliServeHandle> {
  const server = createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => chunks.push(chunk));
    req.on("end", () => {
      const headers: Record<string, string> = {};
      for (const [key, value] of Object.entries(req.headers)) {
        if (typeof value === "string") headers[key] = value;
      }
      void opts.handler({
        method: req.method ?? "GET",
        url: req.url ?? "/",
        headers,
        body: new Uint8Array(Buffer.concat(chunks)),
      }).then((out) => {
        res.writeHead(out.status, out.headers);
        res.end(out.body ?? "");
      });
    });
  });
  await new Promise<void>((resolve) => server.listen(opts.port, opts.host, resolve));
  const address = server.address();
  const port = typeof address === "object" && address !== null ? address.port : opts.port;
  opts.signal?.addEventListener("abort", () => server.close());
  return { port, close: () => new Promise((resolve) => server.close(() => resolve())) };
}

const io: CliIo = {
  env: process.env,
  fetch: (url, init) => fetch(url, init),
  stdout: (text) => process.stdout.write(text),
  stderr: (text) => process.stderr.write(text),
  stdin: readStdin,
  readFile: (path) => readFile(path),
  sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
  now: () => Date.now(),
  loadCommand,
  serve,
  onInterrupt: (handler) => {
    process.on("SIGINT", handler);
    return () => process.off("SIGINT", handler);
  },
};

process.exitCode = await runCli(CLI_SPEC, process.argv.slice(2), io);
