// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliSpec } from './core/model.js';
import { CATALOG } from './catalog.js';

export const CLI_SPEC: CliSpec = {
  auth: [
    {
      name: "api_key",
      type: "apiKey",
      in: "header",
      wireName: "Parcel-API-Key",
      env: "PARCEL_EVENTS_API_KEY",
      valuePrefix: null,
      flag: "api-key"
    },
    {
      name: "bearer_token",
      type: "bearer",
      env: "PARCEL_EVENTS_BEARER_TOKEN",
      flag: "token"
    }
  ],
  authAnyOf: [
    [
      "api_key"
    ],
    [
      "bearer_token"
    ]
  ],
  authDeclared: true,
  authProposed: false,
  authRefused: [],
  authUnused: [],
  baseUrl: "https://api.parcel-events.example",
  baseUrlEnv: "PARCEL_EVENTS_CLI_BASE_URL",
  bin: "parcel-events-cli",
  defaultTimeoutMs: 45000,
  idempotencyHeader: "Idempotency-Key",
  provenance: {
    bundleSha: "718301da46c738b32926ec2a4c2d0bf902b5606f1f4e64b38d3f831ea468bdea",
    cliKernelVersion: "1.5.0",
    configSha: "5fae08d3702fa94e5df38edcc00652963d60db22d094042224b3e25750a054b0",
    generator: "@doctorine/sdk-codegen",
    generatorVersion: "0.4.2",
    irSha: "7b199fcaadfbf3eb638aa931b3520b5cc2d77f3ce08ff6ce4df6227f0db6195a",
    language: "cli",
    package: {
      name: "@sdkfixturelab260904/parcel-events-cli",
      version: "0.1.1"
    },
    sdkSha: "914f7a0c37c0ea516760aba394ac8157719716dfd43df144157c02293e5bb7c4"
  },
  retries: {
    enabled: true,
    maxRetries: 3,
    initialDelayMs: 250,
    maxDelayMs: 8000,
    maxElapsedMs: 60000,
    exponent: 2,
    statusCodes: [
      408,
      409,
      429,
      "5XX"
    ],
    retryConnectionErrors: true
  },
  title: "Parcel Events Sandbox API",
  version: "0.1.1",
  webhookConvention: null,
  catalog: CATALOG,
  commands: [],
} as const as unknown as CliSpec;
