// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliSpec } from './core/model.js';
import { CATALOG } from './catalog.js';

export const CLI_SPEC: CliSpec = {
  auth: [
    {
      name: "api_key",
      type: "apiKey",
      in: "header",
      wireName: "Parcel-API-Key",
      env: "PARCEL_EVENTS_API_KEY",
      valuePrefix: null,
      flag: "api-key"
    },
    {
      name: "bearer_token",
      type: "bearer",
      env: "PARCEL_EVENTS_BEARER_TOKEN",
      flag: "token"
    }
  ],
  authAnyOf: [
    [
      "api_key"
    ],
    [
      "bearer_token"
    ]
  ],
  authDeclared: true,
  authProposed: false,
  authRefused: [],
  authUnused: [],
  baseUrl: "https://api.parcel-events.example",
  baseUrlEnv: "PARCEL_EVENTS_CLI_BASE_URL",
  bin: "parcel-events-cli",
  defaultTimeoutMs: 45000,
  idempotencyHeader: "Idempotency-Key",
  provenance: {
    bundleSha: "6196b4f93c0d72651cd04f49afe07a1bcb677c70fd4d83ea04111af4279ba8fa",
    cliKernelVersion: "1.8.4",
    configSha: "3b30b7bffa895fb980dad02715f00f4e9bfa44b0a1609697a9abc1366c009a3d",
    generator: "@doctorine/sdk-codegen",
    generatorVersion: "0.9.1",
    irSha: "e21b8fd9ceb7e953777c59e3b18e411c0cfdab77418df6ab5c5f73910962ac2e",
    language: "cli",
    package: {
      name: "@sdkfixturelab260904/parcel-events-cli",
      version: "1.2.0"
    },
    sdkSha: "75da4da75163fdd0855af0269fe76a888d048dabc16e6fc180f9c2fa0b43da3e"
  },
  retries: {
    enabled: true,
    maxRetries: 3,
    initialDelayMs: 250,
    maxDelayMs: 8000,
    maxElapsedMs: 60000,
    exponent: 2,
    statusCodes: [
      408,
      409,
      429,
      "5XX"
    ],
    retryConnectionErrors: true
  },
  title: "Parcel Events Sandbox API",
  version: "1.2.0",
  webhookConvention: null,
  catalog: CATALOG,
  commands: [],
} as const as unknown as CliSpec;
