// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliSpec } from './core/model.js';
import { CATALOG } from './catalog.js';

export const CLI_SPEC: CliSpec = {
  auth: [
    {
      name: "api_key",
      type: "apiKey",
      in: "header",
      wireName: "Parcel-API-Key",
      env: "PARCEL_EVENTS_API_KEY",
      valuePrefix: null,
      flag: "api-key"
    },
    {
      name: "bearer_token",
      type: "bearer",
      env: "PARCEL_EVENTS_BEARER_TOKEN",
      flag: "token"
    }
  ],
  authAnyOf: [
    [
      "api_key"
    ],
    [
      "bearer_token"
    ]
  ],
  authDeclared: true,
  authProposed: false,
  authRefused: [],
  authUnused: [],
  baseUrl: "https://api.parcel-events.example",
  baseUrlEnv: "PARCEL_EVENTS_CLI_BASE_URL",
  bin: "parcel-events-cli",
  defaultTimeoutMs: 45000,
  idempotencyHeader: "Idempotency-Key",
  provenance: {
    bundleSha: "718301da46c738b32926ec2a4c2d0bf902b5606f1f4e64b38d3f831ea468bdea",
    cliKernelVersion: "1.8.4",
    configSha: "e78a9ca4ab575d01bcd373f9bd8e82353d460254fb55fded787e806540410d7d",
    generator: "@doctorine/sdk-codegen",
    generatorVersion: "0.9.1",
    irSha: "f8aace4f9c1f5bf1a6fa8c592bc1b33d836d745ee330a65c24afe1bd89e9d728",
    language: "cli",
    package: {
      name: "@sdkfixturelab260904/parcel-events-cli",
      version: "1.1.0"
    },
    sdkSha: "9e2e9910595c4fb37a95b48344eadba627f5b58c2f714f13c9cb7b4220ec14f4"
  },
  retries: {
    enabled: true,
    maxRetries: 3,
    initialDelayMs: 250,
    maxDelayMs: 8000,
    maxElapsedMs: 60000,
    exponent: 2,
    statusCodes: [
      408,
      409,
      429,
      "5XX"
    ],
    retryConnectionErrors: true
  },
  title: "Parcel Events Sandbox API",
  version: "1.1.0",
  webhookConvention: null,
  catalog: CATALOG,
  commands: [],
} as const as unknown as CliSpec;
