// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { CliCommandSpec } from './core/model.js';
import { CATALOG } from './catalog.js';

const LOADERS: Record<string, () => Promise<readonly CliCommandSpec[]>> = {
  "src/commands/labels.ts": () => import("./commands/labels.js").then((mod) => mod.LABELS_COMMANDS),
  "src/commands/pickups.ts": () => import("./commands/pickups.js").then((mod) => mod.PICKUPS_COMMANDS),
  "src/commands/rates.ts": () => import("./commands/rates.js").then((mod) => mod.RATES_COMMANDS),
  "src/commands/retrieve.ts": () => import("./commands/retrieve.js").then((mod) => mod.RETRIEVE_COMMANDS),
  "src/commands/shipments.ts": () => import("./commands/shipments.js").then((mod) => mod.SHIPMENTS_COMMANDS),
  "src/commands/webhook-endpoints.ts": () => import("./commands/webhook-endpoints.js").then((mod) => mod.WEBHOOK_ENDPOINTS_COMMANDS),
};

const SCHEMAS: Record<string, () => Promise<unknown>> = {
  "schemas/delete-v1-pickups-validation.json": () => import("./schemas/delete-v1-pickups-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/delete-v1-shipments-validation.json": () => import("./schemas/delete-v1-shipments-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/delete-v1-webhook-endpoints-validation.json": () => import("./schemas/delete-v1-webhook-endpoints-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-labels-validation.json": () => import("./schemas/get-v1-labels-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-pickups-validation-2.json": () => import("./schemas/get-v1-pickups-validation-2.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-pickups-validation.json": () => import("./schemas/get-v1-pickups-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-shipments-events-validation.json": () => import("./schemas/get-v1-shipments-events-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-shipments-validation-2.json": () => import("./schemas/get-v1-shipments-validation-2.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-shipments-validation.json": () => import("./schemas/get-v1-shipments-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-tracking-validation.json": () => import("./schemas/get-v1-tracking-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-webhook-endpoints-validation-2.json": () => import("./schemas/get-v1-webhook-endpoints-validation-2.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/get-v1-webhook-endpoints-validation.json": () => import("./schemas/get-v1-webhook-endpoints-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/patch-v1-shipments-validation.json": () => import("./schemas/patch-v1-shipments-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/patch-v1-webhook-endpoints-validation.json": () => import("./schemas/patch-v1-webhook-endpoints-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/post-v1-labels-validation.json": () => import("./schemas/post-v1-labels-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/post-v1-pickups-validation.json": () => import("./schemas/post-v1-pickups-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/post-v1-rates-quote-validation.json": () => import("./schemas/post-v1-rates-quote-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/post-v1-shipments-validation.json": () => import("./schemas/post-v1-shipments-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
  "schemas/post-v1-webhook-endpoints-validation.json": () => import("./schemas/post-v1-webhook-endpoints-validation.json", { with: { type: 'json' } }).then((mod) => mod.default),
};

async function resolveSchema(schema: unknown): Promise<unknown> {
  const ref = schema !== null && typeof schema === 'object' && !Array.isArray(schema)
    ? (schema as { $ref?: unknown }).$ref : undefined;
  if (typeof ref !== 'string') return schema;
  const loader = SCHEMAS[ref];
  if (loader === undefined) throw new Error(`missing schema ${ref}`);
  return loader();
}

export async function loadCommand(id: string): Promise<CliCommandSpec> {
  const entry = CATALOG.find((item) => item.id === id);
  if (entry === undefined) throw new Error(`unknown command ${id}`);
  const loaded = await LOADERS[entry.shard]?.();
  const found = loaded?.find((item) => item.id === id);
  if (found === undefined) throw new Error(`missing command ${id}`);
  const [inputSchema, validationSchema] = await Promise.all([resolveSchema(found.inputSchema), resolveSchema(found.validationSchema)]);
  return { ...found, inputSchema, validationSchema };
}
