// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CliCommandSpec } from './core/model.js';
import { CATALOG } from './catalog.js';

const LOADERS: Record<string, () => Promise<readonly CliCommandSpec[]>> = {
  "src/commands/labels.ts": () => import("./commands/labels.js").then((mod) => mod.LABELS_COMMANDS),
  "src/commands/pickups.ts": () => import("./commands/pickups.js").then((mod) => mod.PICKUPS_COMMANDS),
  "src/commands/rates.ts": () => import("./commands/rates.js").then((mod) => mod.RATES_COMMANDS),
  "src/commands/retrieve.ts": () => import("./commands/retrieve.js").then((mod) => mod.RETRIEVE_COMMANDS),
  "src/commands/shipments.ts": () => import("./commands/shipments.js").then((mod) => mod.SHIPMENTS_COMMANDS),
  "src/commands/webhook-endpoints.ts": () => import("./commands/webhook-endpoints.js").then((mod) => mod.WEBHOOK_ENDPOINTS_COMMANDS),
};

function resolveSchema(command: CliCommandSpec): CliCommandSpec {
  const ref = command.inputSchema !== null && typeof command.inputSchema === 'object' && !Array.isArray(command.inputSchema)
    ? (command.inputSchema as { $ref?: unknown }).$ref
    : undefined;
  if (typeof ref !== 'string') return command;
  const raw = readFileSync(join(dirname(fileURLToPath(import.meta.url)), ref), 'utf8');
  return { ...command, inputSchema: JSON.parse(raw) as unknown };
}

export async function loadCommand(id: string): Promise<CliCommandSpec> {
  const entry = CATALOG.find((item) => item.id === id);
  if (entry === undefined) throw new Error(`unknown command ${id}`);
  const loaded = await LOADERS[entry.shard]?.();
  const found = loaded?.find((item) => item.id === id);
  if (found === undefined) throw new Error(`missing command ${id}`);
  return resolveSchema(found);
}
